# Generated by Django 4.2.16 on 2024-11-26 08:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_category_table_alter_product_table'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='Cart',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'корзину', 'verbose_name_plural': 'корзины'},
        ),
    ]
