# Generated by Django 4.2.16 on 2024-11-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='created_timestemps',
            new_name='created_timestemp',
        ),
    ]
